version: 2
jobs:
  E2ETest:
    docker:
      # Image with required cypres deps
      - image: cypress/included:3.2.0
        environment:
          # Enables colored output
          TERM: xterm
    parallelism: 1
    steps:
      - checkout
      # installs cypress deps onto container ( I think )
      - run: yarn install --frozen-lockfile
      - run:
          name: "Runs end to end tests"
          command: "yarn run E2ETest"
      - store_artifacts:
          path: cypress/videos/odysseyTests
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
workflows:
  version: 2
  e2e_tests:
    jobs:
      - e2e_tests
  build:
    jobs:
      - build
