version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  E2ETest:
    docker:
      # Image with required cypres deps
      - image: cypress/included:3.2.0
        environment:
          # Enables colored output
          TERM: xterm
    parallelism: 1
    steps:
      - checkout
      # installs cypress deps onto container ( I think )
      - run: yarn install --frozen-lockfile
      - run:
          name: "Runs end to end tests"
          command: "yarn run E2ETest"
      - store_artifacts:
          path: cypress/videos/odysseyTests
  slackNotify:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0
      - slack/status:
          fail_only: true
          mentions: ""
          only_for_branches: "staging"
          webhook: "${SLACK_WEBHOOK}"
  customBuild:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "Installing"
          command: yarn install
      - run:
          name: "Building"
          command: yarn build
      - slack/status:
          fail_only: true
workflows:
  version: 2.1
  e2e_tests:
    jobs:
      - E2ETest
  slackNotify:
    jobs:
      - slackNotify
  customBuild:
    jobs:
      - customBuild
