version: 2
jobs:
  E2ETest:
    docker:
      # Image with required cypres deps
      - image: cypress/base:8
        environment:
          # Enables colored output
          TERM: xterm
    parallelism: 1
    steps:
      - checkout
      # installs cypress deps onto container ( I think )
      - run: yarn install --frozen-lockfile
      - run:
          name: "Runs end to end tests"
          command: "yarn run E2ETest"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - run: yarn run test
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo npm install -g now
      - run:
          name: Deploy to Now
          command: cd client && now --token $ZEIT_TOKEN --local-config now.production.json --prod
workflows:
  version: 2
  e2e_tests:
    jobs:
      - E2ETest
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
