version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - run: yarn run test
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo npm install -g now
      - run: 
          name: Deploy to Now
          command: cd client && now --token $ZEIT_TOKEN --local-config now.production.json --prod
workflows:
  version: 2
  test_deploy:
    jobs:
      - client-test
      - server-test
      - client-deploy:
          requires:
            - client-test
          filters:
            branches:
              only:
                - master
      - server-deploy:
          requires:
            - server-test
          filters:
            branches:
              only:
                - master