name: "Jest + Test Coverage"

on:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  # unit tests
  tests:
    name: "Jest + Coverage Tests"
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
      DEV_DB_PORT: ${{ secrets.DEV_DB_PORT }}
      DEV_DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
      DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      DEV_DB_NAME: ${{ secrets.DEV_DB_NAME }}
      DEV_DB_HOSTNAME: ${{ secrets.DEV_DB_HOSTNAME }}
      DEV_DB_DIALECT: ${{ secrets.DEV_DB_DIALECT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - run: yarn jest
      - run: yarn test
