name: "Jest + Test Coverage"

on:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  # unit tests
  tests:
    name: "Jest + Coverage Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - run: yarn jest
      - run: yarn test
