name: "Jest + Test Coverage"

on:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  # unit tests
  tests:
    name: "Jest + Coverage Tests"
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - run: yarn jest
      - run: yarn test
